version: "3.7"



services:
    #databse service
    mysql-db:
        image: mysql:8.0.25
        container_name: mysql-db
        environment:
            - MYSQL_ROOT_PASSWORD=root
            - MYSQL_DATABASE=backend_db
            - MYSQL_USER=spring
            - MYSQL_PASSWORD=root
        restart: always
        networks:
            - mysql_db_network

    #backend
    gallery-backend:
        build:
            context: ./backend
            target: gallery-application
        image: gallery/backend
        container_name: gallery-backend
        ports:
            - 8080:8080
        depends_on:
            - mysql-db
        command: ["./wait-for-it.sh", "mysql-db:3360", "--", "echo MYSQL Databse is up !", "&&", "java", "-jar", "/usr/local/lib/gallery.jar"]
        networks:
#            - frontend_network
            - mysql_db_network

    #gallery-frontend:
    # build: ./frontend
    # image: gallery/frontend
    # container_name: gallery-frontend
    # ports:
    #     - 8089:8089
    # depends_on:
    #     - gallery-backend
    # networks:
    #     - frontend_network

networks:
    mysql_db_network:
        driver: bridge
    #frontend_network:
    #   driver: bridge
